import { USER_ROLES } from '@devStack/enums/user-role-enums'

import { MENU_KEYS } from '../constants/MenuKeys'

// export const USER_ROLES = {
//   ADMIN: 'admin',
//   USER: 'user',
//   SUPER_ADMIN: 'superadmin',
// }

export const MENU_PERMISSIONS = {
  [MENU_KEYS.HOME]: [USER_ROLES.ADMIN, USER_ROLES.USER, USER_ROLES.SUPER_ADMIN],

  [MENU_KEYS.ABOUT]: [USER_ROLES.ADMIN, USER_ROLES.USER, USER_ROLES.SUPER_ADMIN],

  [MENU_KEYS.MY_PROFILE]: [USER_ROLES.ADMIN, USER_ROLES.USER, USER_ROLES.SUPER_ADMIN],

  [MENU_KEYS.ADD_USER]: [USER_ROLES.ADMIN, USER_ROLES.USER, USER_ROLES.SUPER_ADMIN],

  [MENU_KEYS.ROLE_MANAGEMENT]: [USER_ROLES.ADMIN, USER_ROLES.USER, USER_ROLES.SUPER_ADMIN],

  [MENU_KEYS.TASK_MANAGEMENT]: [USER_ROLES.ADMIN, USER_ROLES.USER, USER_ROLES.SUPER_ADMIN],
  [MENU_KEYS.KNOWLEDGE_VAULT]: [USER_ROLES.ADMIN, USER_ROLES.USER, USER_ROLES.SUPER_ADMIN],
  [MENU_KEYS.KNOWLEDGE_VAULT_NOTE]: [USER_ROLES.ADMIN, USER_ROLES.USER, USER_ROLES.SUPER_ADMIN],
}

export const hasMenuPermission = (menuKey, userRole) => {
  const allowedRoles = MENU_PERMISSIONS[menuKey]
  return allowedRoles ? allowedRoles.includes(userRole) : false
}

export default MENU_PERMISSIONS
